<?php

namespace Proxies\__CG__\ReclamationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \ReclamationBundle\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'categorie', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'dateajout', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'ancienprix', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'nvprix', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'nomp', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'description', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'stock', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'ptfidelite', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'image', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'estachete', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'productImg', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'prix'];
        }

        return ['__isInitialized__', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'id', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'categorie', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'dateajout', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'ancienprix', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'nvprix', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'nomp', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'description', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'stock', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'ptfidelite', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'image', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'estachete', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'productImg', '' . "\0" . 'ReclamationBundle\\Entity\\Produit' . "\0" . 'prix'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie($categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateajout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateajout', []);

        return parent::getDateajout();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateajout($dateajout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateajout', [$dateajout]);

        return parent::setDateajout($dateajout);
    }

    /**
     * {@inheritDoc}
     */
    public function getAncienprix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAncienprix', []);

        return parent::getAncienprix();
    }

    /**
     * {@inheritDoc}
     */
    public function setAncienprix($ancienprix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAncienprix', [$ancienprix]);

        return parent::setAncienprix($ancienprix);
    }

    /**
     * {@inheritDoc}
     */
    public function getNvprix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNvprix', []);

        return parent::getNvprix();
    }

    /**
     * {@inheritDoc}
     */
    public function setNvprix($nvprix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNvprix', [$nvprix]);

        return parent::setNvprix($nvprix);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomp', []);

        return parent::getNomp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomp($nomp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomp', [$nomp]);

        return parent::setNomp($nomp);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', []);

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock($stock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', [$stock]);

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getPtfidelite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPtfidelite', []);

        return parent::getPtfidelite();
    }

    /**
     * {@inheritDoc}
     */
    public function setPtfidelite($ptfidelite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPtfidelite', [$ptfidelite]);

        return parent::setPtfidelite($ptfidelite);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function isEstachete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEstachete', []);

        return parent::isEstachete();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstachete($estachete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstachete', [$estachete]);

        return parent::setEstachete($estachete);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductImg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductImg', []);

        return parent::getProductImg();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductImg($productImg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductImg', [$productImg]);

        return parent::setProductImg($productImg);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

}
